<a href="https://colab.research.google.com/github/PandiRaja18/AI/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numby** Basics with **Matrix**

In [2]:
import numpy as np
#one dimentional matrix (we said)
a=np.array([1,2,3,4])
print(a)
print(a.shape) #Elements in a row
print(type(a)) #numpy nd array is also known as Matrix


[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [5]:
b=np.array([1.1,2.2,3.3])
print(b)
print(b.shape) #Elements in a row
print(type(b))

[1.1 2.2 3.3]
(3,)
<class 'numpy.ndarray'>


Access elements

In [6]:
print(a[0])
print(b[2])
print(type(a[2]))
print(type(b[1]))

1
3.3
<class 'numpy.int64'>
<class 'numpy.float64'>


**2X2** **Matrix**

In [9]:
c=np.array([[1,2],[3,4]])
print(c)
print("Shape of the matrix is",c.shape)

[[1 2]
 [3 4]]
Shape of the matrix is (2, 2)


In [3]:
d=np.ones((2,2)) #Matrix of size 2X2 filled with 1's
print(d)
print("Shape of the Matrix is ",d.shape)
print(type(d))
print(type(d[0][0]))


[[1. 1.]
 [1. 1.]]
Shape of the Matrix is  (2, 2)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [12]:
e=np.zeros((4,4)) #Matrix of size 4 X 4 filled with 0's
print(e)
print("Shape of the Matrix is ",e.shape)
print(type(e))
print(type(e[1][1])) #The matrix is created by Float Datatype.

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of the Matrix is  (4, 4)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


**Random** **matrix**

In [10]:
# A 2 x 2 Matrix created with random numbers
f=np.random.random((2,2)) 
print("The matrix created Randomly")
print(f)
print(f.shape)

The matrix created Randomly
[[0.96803881 0.95736395]
 [0.50759691 0.03136637]]
(2, 2)


**Expand Dimensions**

In [16]:
#1 x 3 Matrix
arr=np.array([100,200,300])
print("Given Matrix :")
print(arr)
print(arr.shape)

#Insert a new axis along the row
b=np.expand_dims(arr,axis=0)

#Insert a new axis along the column
c=np.expand_dims(arr,axis=1)

print("Extended Matrix along Row :")
print(b)
print(b.shape)
print("Extended Matrix along Column :")
print(c)
print(c.shape)

#The above both function outputs like transpose of a matrix. 

Given Matrix :
[100 200 300]
(3,)
Extended Matrix along Row :
[[100 200 300]]
(1, 3)
Extended Matrix along Column :
[[100]
 [200]
 [300]]
(3, 1)


**Unique** **Elements**

In [19]:
m_arr=np.array([1,2,1,1,3])

#Get the unique elements and their Indices
n,indices = np.unique(m_arr,return_index=True)
print("Unique Elements :",n)
print("Their Indices   :",indices) 

"""Application :
we can use this numpy to communicate the data within the Library
"""


Unique Elements : [1 2 3]
Their Indices   : [0 1 4]
